//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class commercialEntities2 : DbContext
    {
        public commercialEntities2()
            : base("name=commercialEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articles> articles { get; set; }
        public virtual DbSet<clientel> clientel { get; set; }
        public virtual DbSet<commandes> commandes { get; set; }
        public virtual DbSet<compose> compose { get; set; }
        public virtual DbSet<detail_cde> detail_cde { get; set; }
        public virtual DbSet<vendeur> vendeur { get; set; }
    
        public virtual int articles_augm_prix(Nullable<double> augmente)
        {
            var augmenteParameter = augmente.HasValue ?
                new ObjectParameter("augmente", augmente) :
                new ObjectParameter("augmente", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("articles_augm_prix", augmenteParameter);
        }
    }
}
